---
name: activejob
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 8149bc3fc0f720d935dc0592dc8886e03052f65f
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
