module Barley
class Serializer
  @cache: bool
  @context: Struct[untyped]
  @expires_in: ActiveSupport::Duration
  @root: bool

  attr_accessor self.defined_attributes: Array[Symbol]
  attr_accessor context: Struct[untyped]
  attr_accessor object: ActiveRecord::Base
  def self.attributes: (*(Symbol | Hash[Symbol, untyped]) keys) -> untyped
  def self.attribute: (Symbol key, ?key_name: Symbol | nil, ?type: nil) ?{ () -> void } -> [untyped]
  def self.one: (Symbol key, ?key_name: Symbol, ?serializer: Serializer, ?cache: bool | Hash[Symbol, ActiveSupport::Duration]) ?{ () -> void } -> (Hash[untyped, untyped] | [untyped])
  def self.many: (Symbol key, ?key_name: Symbol, ?serializer: Serializer, ?cache: bool | Hash[Symbol, ActiveSupport::Duration]) ?{ () -> void } -> Array[untyped]
  def self.set_class_iv: (Symbol iv, Symbol key) -> [untyped]
  def initialize: (untyped object, ?cache: bool | Hash[Symbol, ActiveSupport::Duration], ?root: bool) -> void
  def serializable_hash: -> Hash[Symbol, untyped]
  def clear_cache: (?key: String) -> untyped
  def with_context:(*(Hash[Symbol, untyped])) -> self

  private
  def cache_base_key: -> String
  def defined_attributes: -> Array[Symbol]
  def _serializable_hash: -> Hash[Symbol, untyped]

  def root_key: -> Symbol
end
end

