module Barley
  module Serializable
    def serializer: (ActiveRecord::Base klass, ?cache: bool | Hash[Symbol, ActiveSupport::Duration]) -> untyped
    def as_json: (?options: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]
  end
end
